elements {
    n, z=0, name=Neutron
    H, z=1, name=Hydrogen
    He, z=2, name=Helium
    Li, z=3, name=Lithium
    Be, z=4, name=Beryllium
    B, z=5, name=Boron
    C, z=6, name=Carbon
    N, z=7, name=Nitrogen
    O, z=8, name=Oxygen
    F, z=9, name=Fluorine
    Ne, z=10, name=Neon
    Na, z=11, name=Sodium
    Mg, z=12, name=Magnesium
    Al, z=13, name=Aluminium
    Si, z=14, name=Silicon
    P, z=15, name=Phosphorus
    S, z=16, name=Sulfur
    Cl, z=17, name=Chlorine
    Ar, z=18, name=Argon
    K, z=19, name=Potassium
    Ca, z=20, name=Calcium
    Sc, z=21, name=Scandium
    Ti, z=22, name=Titanium
    V, z=23, name=Vanadium
    Cr, z=24, name=Chromium
    Mn, z=25, name=Manganese
    Fe, z=26, name=Iron
    Co, z=27, name=Cobalt
    Ni, z=28, name=Nickel
    Cu, z=29, name=Copper
    Zn, z=30, name=Zinc
    Ga, z=31, name=Gallium
    Ge, z=32, name=Germanium
    As, z=33, name=Arsenic
    Se, z=34, name=Selenium
    Br, z=35, name=Bromine
    Kr, z=36, name=Krypton
    Rb, z=37, name=Rubidium
    Sr, z=38, name=Strontium
    Y, z=39, name=Yttrium
    Zr, z=40, name=Zirconium
    Nb, z=41, name=Niobium
    Mo, z=42, name=Molybdenum
    Tc, z=43, name=Technetium
    Ru, z=44, name=Ruthenium
    Rh, z=45, name=Rhodium
    Pd, z=46, name=Palladium
    Ag, z=47, name=Silver
    Cd, z=48, name=Cadmium
    In, z=49, name=Indium
    Sn, z=50, name=Tin
    Sb, z=51, name=Antimony
    Te, z=52, name=Tellurium
    I, z=53, name=Iodine
    Xe, z=54, name=Xenon
    Cs, z=55, name=Cesium
    Ba, z=56, name=Barium
    La, z=57, name=Lanthanum
    Ce, z=58, name=Cerium
    Pr, z=59, name=Praseodymium
    Nd, z=60, name=Neodymium
    Pm, z=61, name=Promethium
    Sm, z=62, name=Samarium
    Eu, z=63, name=Europium
    Gd, z=64, name=Gadolinium
    Tb, z=65, name=Terbium
    Dy, z=66, name=Dysprosium
    Ho, z=67, name=Holmium
    Er, z=68, name=Erbium
    Tm, z=69, name=Thulium
    Yb, z=70, name=Ytterbium
    Lu, z=71, name=Lutetium
    Hf, z=72, name=Hafnium
    Ta, z=73, name=Tantalum
    W, z=74, name=Tungsten
    Re, z=75, name=Rhenium
    Os, z=76, name=Osmium
    Ir, z=77, name=Iridium
    Pt, z=78, name=Platinum
    Au, z=79, name=Gold
    Hg, z=80, name=Mercury
    Tl, z=81, name=Thallium
    Pb, z=82, name=Lead
    Bi, z=83, name=Bismuth
    Po, z=84, name=Polonium
    At, z=85, name=Astatine
    Rn, z=86, name=Radon
    Fr, z=87, name=Francium
    Ra, z=88, name=Radium
    Ac, z=89, name=Actinium
    Th, z=90, name=Thorium
    Pa, z=91, name=Protactinium
    U, z=92, name=Uranium
    Np, z=93, name=Neptunium
    Pu, z=94, name=Plutonium
    Am, z=95, name=Americium
    Cm, z=96, name=Curium
    Bk, z=97, name=Berkelium
    Cf, z=98, name=Californium
    Es, z=99, name=Einsteinium
    Fm, z=100, name=Fermium
    Md, z=101, name=Mendelevium
    No, z=102, name=Nobelium
    Lr, z=103, name=Lawrencium
    Rf, z=104, name=Rutherfordium
    Db, z=105, name=Dubnium
    Sg, z=106, name=Seaborgium
    Bh, z=107, name=Bohrium
    Hs, z=108, name=Hassium
    Mt, z=109, name=Meitnerium
    Ds, z=110, name=Darmstadtium
    Rg, z=111, name=Roentgenium
    Cn, z=112, name=Copernicium
    Nh, z=113, name=Nihonium
    Fl, z=114, name=Flerovium
    Mc, z=115, name=Moscovium
    Lv, z=116, name=Livermorium
    Ts, z=117, name=Tennessine
    Og, z=118, name=Oganesson
}
